language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ruby-head
env:
  - "rack=1.3.6"
  - "rack=1.4.1"
  - "rack=master"
  - "tilt=1.3.3"
  - "tilt=master"
matrix:
  allow_failures:
    - rvm: ruby-head
notifications:
  recipients:
    - akirapanda@newnil.com